apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2022-07-01T18:15:28Z"
  name: default
  namespace: kube-system
  resourceVersion: "358"
  uid: 1c1560ee-2e76-4c3f-bed4-91b5ddafe3a8
secrets:
- name: default-token-l57sp
