apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"policy/v1beta1","kind":"PodDisruptionBudget","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","kubernetes.io/cluster-service":"true"},"name":"konnectivity-agent","namespace":"kube-system"},"spec":{"minAvailable":1,"selector":{"matchLabels":{"app":"konnectivity-agent"}}}}
  creationTimestamp: "2022-07-01T18:15:42Z"
  generation: 1
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/cluster-service: "true"
  name: konnectivity-agent
  namespace: kube-system
  resourceVersion: "1919"
  uid: e77af3a8-da1c-4b12-b27d-d871a996cc53
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: konnectivity-agent
status:
  conditions:
  - lastTransitionTime: "2022-07-01T18:19:14Z"
    message: ""
    observedGeneration: 1
    reason: SufficientPods
    status: "True"
    type: DisruptionAllowed
  currentHealthy: 2
  desiredHealthy: 1
  disruptionsAllowed: 1
  expectedPods: 2
  observedGeneration: 1
