# Statefull because it maintains a sticky session with its pods
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: efk
  labels:
    app: "elasticsearch"
spec:
  serviceName: elasticsearch-headless
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: "elasticsearch"
      namespace: efk
      labels:
        app: "elasticsearch"
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      automountServiceAccountToken: true
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - "elasticsearch"
              topologyKey: kubernetes.io/hostname
      enableServiceLinks: true
      terminationGracePeriodSeconds: 60
      containers:
        - name: "elasticsearch"
          image: "docker.elastic.co/elasticsearch/elasticsearch:8.3.1"
          imagePullPolicy: "IfNotPresent"
          securityContext:
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: transport
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 1000m
          env:
            - name: cluster.name
              value: "elasticsearch"
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: discovery.seed_hosts
              value: "elasticsearch-headless"
            - name: cluster.initial_master_nodes
              value: "elasticsearch-0,elasticsearch-1,elasticsearch-2,"
            - name: network.host
              value: "0.0.0.0"
            - name: xpack.security.enabled
              value: "false"
          volumeMounts:
            - name: "es-data"
              mountPath: /usr/share/elasticsearch/data
      initContainers:
        - name: increase-vm-max-map
          securityContext:
            runAsUser: 0
            privileged: true
          image: "docker.elastic.co/elasticsearch/elasticsearch:8.3.1"
          imagePullPolicy: "IfNotPresent"
          command: [ "sysctl", "-w", "vm.max_map_count=262144" ]
  volumeClaimTemplates:
    - metadata:
        name: "es-data"
        namespace: efk
        labels:
          app: elasticsearch
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
