#https://kubernetes.io/docs/reference/access-authn-authz/rbac/#service-account-permissions
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: efk
  labels:
    app: filebeat