# https://kubernetes.io/docs/reference/access-authn-authz/rbac/#service-account-permissions
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: filebeat
  namespace: efk
  labels:
    app: filebeat
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs: [ "get", "create", "update" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: filebeat-kubeadm-config
  namespace: efk
  labels:
    app: filebeat
rules:
  - apiGroups: [ "" ]
    resources:
      - configmaps
    resourceNames:
      - kubeadm-config
    verbs: [ "get" ]