apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2022-07-01T19:20:07Z"
  creationTimestamp: "2022-07-01T19:18:47Z"
  labels:
    app: kibana
    heritage: Helm
    release: kibana
  name: kibana-kibana
  namespace: default
  resourceVersion: "16073"
  uid: 021fc6d1-a824-476d-80c2-1fff10aa5260
subsets:
- addresses:
  - ip: 10.244.2.6
    nodeName: aks-agentpool-11515983-vmss000002
    targetRef:
      kind: Pod
      name: kibana-kibana-58bc997cc-4vqh2
      namespace: default
      resourceVersion: "16072"
      uid: 5e33e0b0-e448-43d2-9b29-6611b433e35d
  ports:
  - name: http
    port: 5601
    protocol: TCP
