apiVersion: v1
kind: Pod
metadata:
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  creationTimestamp: "2022-07-01T18:15:42Z"
  generateName: coredns-autoscaler-7d56cd888-
  labels:
    k8s-app: coredns-autoscaler
    pod-template-hash: 7d56cd888
  name: coredns-autoscaler-7d56cd888-hpnx4
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: coredns-autoscaler-7d56cd888
    uid: d95fe1d1-bf95-4797-872a-381ac8de39cc
  resourceVersion: "1382"
  uid: d75afafe-3c01-4883-b446-12498a9328c1
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: kubernetes.azure.com/mode
            operator: In
            values:
            - system
        weight: 100
  containers:
  - command:
    - /cluster-proportional-autoscaler
    - --namespace=kube-system
    - --configmap=coredns-autoscaler
    - --target=deployment/coredns
    - --default-params={"ladder":{"coresToReplicas":[[1,2],[512,3],[1024,4],[2048,5]],"nodesToReplicas":[[1,2],[8,3],[16,4],[32,5]]}}
    - --logtostderr=true
    - --v=2
    env:
    - name: KUBERNETES_PORT_443_TCP_ADDR
      value: acldys-7ea05377.hcp.westeurope.azmk8s.io
    - name: KUBERNETES_PORT
      value: tcp://acldys-7ea05377.hcp.westeurope.azmk8s.io:443
    - name: KUBERNETES_PORT_443_TCP
      value: tcp://acldys-7ea05377.hcp.westeurope.azmk8s.io:443
    - name: KUBERNETES_SERVICE_HOST
      value: acldys-7ea05377.hcp.westeurope.azmk8s.io
    image: mcr.microsoft.com/oss/kubernetes/autoscaler/cluster-proportional-autoscaler:1.8.5
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /last-poll
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: autoscaler
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 20m
        memory: 10Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-9kchs
      readOnly: true
  dnsPolicy: Default
  enableServiceLinks: true
  nodeName: aks-agentpool-11515983-vmss000001
  nodeSelector:
    beta.kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 2000001000
  priorityClassName: system-node-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: coredns-autoscaler
  serviceAccountName: coredns-autoscaler
  terminationGracePeriodSeconds: 30
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 30
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 30
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: kube-api-access-9kchs
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-07-01T18:17:34Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-07-01T18:17:36Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-07-01T18:17:36Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-07-01T18:17:34Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://1a2a9f6a6a00bf620d360b4cc5ecbdae28c1affd692e62448fdef402b0cca330
    image: mcr.microsoft.com/oss/kubernetes/autoscaler/cluster-proportional-autoscaler:1.8.5
    imageID: sha256:67f622f206c864b3e5404c451ffc3febae94ed781fbd0d3c77369963e42244f9
    lastState: {}
    name: autoscaler
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-07-01T18:17:36Z"
  hostIP: 10.224.0.5
  phase: Running
  podIP: 10.244.1.3
  podIPs:
  - ip: 10.244.1.3
  qosClass: Burstable
  startTime: "2022-07-01T18:17:34Z"
