apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-07-01T18:16:24Z"
  generateName: csi-azurefile-node-
  labels:
    app: csi-azurefile-node
    controller-revision-hash: 7cfc8dd6d7
    pod-template-generation: "1"
  name: csi-azurefile-node-l5pq4
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: csi-azurefile-node
    uid: f4e63461-fbb7-48aa-9696-d66a4470b7c2
  resourceVersion: "991"
  uid: 0ff91ae0-5193-4512-b4b3-76a1b9a40117
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - aks-agentpool-11515983-vmss000001
  containers:
  - args:
    - --csi-address=/csi/csi.sock
    - --probe-timeout=3s
    - --health-port=29613
    - --v=2
    env:
    - name: KUBERNETES_PORT_443_TCP_ADDR
      value: acldys-7ea05377.hcp.westeurope.azmk8s.io
    - name: KUBERNETES_PORT
      value: tcp://acldys-7ea05377.hcp.westeurope.azmk8s.io:443
    - name: KUBERNETES_PORT_443_TCP
      value: tcp://acldys-7ea05377.hcp.westeurope.azmk8s.io:443
    - name: KUBERNETES_SERVICE_HOST
      value: acldys-7ea05377.hcp.westeurope.azmk8s.io
    image: mcr.microsoft.com/oss/kubernetes-csi/livenessprobe:v2.6.0
    imagePullPolicy: IfNotPresent
    name: liveness-probe
    resources:
      limits:
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 20Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /csi
      name: socket-dir
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-tckcm
      readOnly: true
  - args:
    - --csi-address=$(ADDRESS)
    - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
    - --v=2
    env:
    - name: ADDRESS
      value: /csi/csi.sock
    - name: DRIVER_REG_SOCK_PATH
      value: /var/lib/kubelet/plugins/file.csi.azure.com/csi.sock
    - name: KUBERNETES_PORT_443_TCP_ADDR
      value: acldys-7ea05377.hcp.westeurope.azmk8s.io
    - name: KUBERNETES_PORT
      value: tcp://acldys-7ea05377.hcp.westeurope.azmk8s.io:443
    - name: KUBERNETES_PORT_443_TCP
      value: tcp://acldys-7ea05377.hcp.westeurope.azmk8s.io:443
    - name: KUBERNETES_SERVICE_HOST
      value: acldys-7ea05377.hcp.westeurope.azmk8s.io
    image: mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar:v2.5.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - /csi-node-driver-registrar
        - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
        - --mode=kubelet-registration-probe
      failureThreshold: 3
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 30
    name: node-driver-registrar
    resources:
      limits:
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 20Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /csi
      name: socket-dir
    - mountPath: /registration
      name: registration-dir
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-tckcm
      readOnly: true
  - args:
    - --v=2
    - --endpoint=$(CSI_ENDPOINT)
    - --nodeid=$(KUBE_NODE_NAME)
    - --metrics-address=0.0.0.0:29615
    - --enable-get-volume-stats=true
    - --mount-permissions=0777
    env:
    - name: AZURE_CREDENTIAL_FILE
      value: /etc/kubernetes/azure.json
    - name: CSI_ENDPOINT
      value: unix:///csi/csi.sock
    - name: KUBE_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: KUBERNETES_PORT_443_TCP_ADDR
      value: acldys-7ea05377.hcp.westeurope.azmk8s.io
    - name: KUBERNETES_PORT
      value: tcp://acldys-7ea05377.hcp.westeurope.azmk8s.io:443
    - name: KUBERNETES_PORT_443_TCP
      value: tcp://acldys-7ea05377.hcp.westeurope.azmk8s.io:443
    - name: KUBERNETES_SERVICE_HOST
      value: acldys-7ea05377.hcp.westeurope.azmk8s.io
    image: mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi:v1.19.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /healthz
        port: healthz
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 10
    name: azurefile
    ports:
    - containerPort: 29613
      hostPort: 29613
      name: healthz
      protocol: TCP
    resources:
      limits:
        memory: 400Mi
      requests:
        cpu: 10m
        memory: 20Mi
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /csi
      name: socket-dir
    - mountPath: /var/lib/kubelet/
      mountPropagation: Bidirectional
      name: mountpoint-dir
    - mountPath: /etc/kubernetes/
      name: azure-cred
    - mountPath: /dev
      name: device-dir
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-tckcm
      readOnly: true
  dnsPolicy: Default
  enableServiceLinks: true
  hostNetwork: true
  nodeName: aks-agentpool-11515983-vmss000001
  preemptionPolicy: PreemptLowerPriority
  priority: 2000001000
  priorityClassName: system-node-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: csi-azurefile-node-sa
  serviceAccountName: csi-azurefile-node-sa
  terminationGracePeriodSeconds: 30
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoExecute
    operator: Exists
  - effect: NoSchedule
    operator: Exists
  volumes:
  - hostPath:
      path: /var/lib/kubelet/plugins/file.csi.azure.com
      type: DirectoryOrCreate
    name: socket-dir
  - hostPath:
      path: /var/lib/kubelet/
      type: DirectoryOrCreate
    name: mountpoint-dir
  - hostPath:
      path: /var/lib/kubelet/plugins_registry/
      type: DirectoryOrCreate
    name: registration-dir
  - hostPath:
      path: /etc/kubernetes/
      type: DirectoryOrCreate
    name: azure-cred
  - hostPath:
      path: /dev
      type: Directory
    name: device-dir
  - name: kube-api-access-tckcm
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-07-01T18:16:25Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-07-01T18:16:37Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-07-01T18:16:37Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-07-01T18:16:24Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://6ec117f35c2be854fb26ae17144910130f4ba400cfd98cd00f67bdbb58ef02fc
    image: mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi:v1.19.0
    imageID: mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi@sha256:52eb5867c901156f0c853c0ff2fc7e6e02858b8cd9479797760ec37bc76ef524
    lastState: {}
    name: azurefile
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-07-01T18:16:37Z"
  - containerID: containerd://9b1c832440c59131cb76002bde4318141046e0ffb09e9a4ea1f7ba11df80956e
    image: mcr.microsoft.com/oss/kubernetes-csi/livenessprobe:v2.6.0
    imageID: sha256:f97059c7b56f8e771da0f91e81e495d8f722125c1342148db5970be7b4c16570
    lastState: {}
    name: liveness-probe
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-07-01T18:16:28Z"
  - containerID: containerd://3d27e3aacf8b47f193afe95db3e1f81603e0cc6c95a182c8f25b93c3c71bcc1d
    image: mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar:v2.5.0
    imageID: sha256:9f080292bc0292635062a424791004c647437fd6cb107580beeb946673d399c8
    lastState: {}
    name: node-driver-registrar
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-07-01T18:16:29Z"
  hostIP: 10.224.0.5
  phase: Running
  podIP: 10.224.0.5
  podIPs:
  - ip: 10.224.0.5
  qosClass: Burstable
  startTime: "2022-07-01T18:16:25Z"
