apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-07-01T18:16:23Z"
  generateName: kube-proxy-
  labels:
    component: kube-proxy
    controller-revision-hash: b59487dd4
    pod-template-generation: "1"
    tier: node
  name: kube-proxy-c7xfk
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: kube-proxy
    uid: ff05f694-519e-4c43-b0f9-8ad7768febed
  resourceVersion: "905"
  uid: 3209f19a-8404-4eeb-9c0d-0aad1e1bd6cf
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - aks-agentpool-11515983-vmss000000
  containers:
  - command:
    - kube-proxy
    - --metrics-bind-address=0.0.0.0:10249
    - --kubeconfig=/var/lib/kubelet/kubeconfig
    - --cluster-cidr=10.244.0.0/16
    - --v=3
    env:
    - name: KUBERNETES_PORT_443_TCP_ADDR
      value: acldys-7ea05377.hcp.westeurope.azmk8s.io
    - name: KUBERNETES_PORT
      value: tcp://acldys-7ea05377.hcp.westeurope.azmk8s.io:443
    - name: KUBERNETES_PORT_443_TCP
      value: tcp://acldys-7ea05377.hcp.westeurope.azmk8s.io:443
    - name: KUBERNETES_SERVICE_HOST
      value: acldys-7ea05377.hcp.westeurope.azmk8s.io
    image: mcr.microsoft.com/oss/kubernetes/kube-proxy:v1.22.6-hotfix.20220330.4
    imagePullPolicy: IfNotPresent
    name: kube-proxy
    resources:
      requests:
        cpu: 100m
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/kubelet
      name: kubeconfig
      readOnly: true
    - mountPath: /etc/kubernetes/certs
      name: certificates
      readOnly: true
    - mountPath: /run/xtables.lock
      name: iptableslock
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-x4ctd
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  nodeName: aks-agentpool-11515983-vmss000000
  preemptionPolicy: PreemptLowerPriority
  priority: 2000001000
  priorityClassName: system-node-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: kube-proxy
  serviceAccountName: kube-proxy
  terminationGracePeriodSeconds: 30
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoExecute
    operator: Exists
  - effect: NoSchedule
    operator: Exists
  volumes:
  - hostPath:
      path: /var/lib/kubelet
      type: ""
    name: kubeconfig
  - hostPath:
      path: /etc/kubernetes/certs
      type: ""
    name: certificates
  - hostPath:
      path: /run/xtables.lock
      type: FileOrCreate
    name: iptableslock
  - name: kube-api-access-x4ctd
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-07-01T18:16:24Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-07-01T18:16:27Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-07-01T18:16:27Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-07-01T18:16:23Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://cb33f3ee3db6b2b0ecf2f82227c9c52b801536c30b8c20d0543643470f7c53b3
    image: mcr.microsoft.com/oss/kubernetes/kube-proxy:v1.22.6-hotfix.20220330.4
    imageID: mcr.microsoft.com/oss/kubernetes/kube-proxy@sha256:b44ee08650f8bb3ec54bf84a8be0f3c60f8d5c1bb4692f7b7edd21a9e4b11c7e
    lastState: {}
    name: kube-proxy
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-07-01T18:16:27Z"
  hostIP: 10.224.0.4
  phase: Running
  podIP: 10.224.0.4
  podIPs:
  - ip: 10.224.0.4
  qosClass: Burstable
  startTime: "2022-07-01T18:16:24Z"
