apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2022-07-01T18:15:20Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system::leader-locking-kube-controller-manager
  namespace: kube-system
  resourceVersion: "193"
  uid: cf9f8574-e44a-4e12-b3de-a73ae46e9b14
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - watch
- apiGroups:
  - ""
  resourceNames:
  - kube-controller-manager
  resources:
  - configmaps
  verbs:
  - get
  - update
