apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  creationTimestamp: "2022-07-01T18:15:26Z"
  name: external-attacher-leader-file-csi-azure-com
  namespace: kube-system
  resourceVersion: "44081"
  uid: f5f648e4-4706-4a69-b621-ac32bdc41158
spec:
  acquireTime: "2022-07-01T18:15:26.490285Z"
  holderIdentity: csi-azurefile-controller-5bf6f9774f-ddfj7
  leaseDurationSeconds: 15
  leaseTransitions: 0
  renewTime: "2022-07-01T21:22:20.467466Z"
