apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"DaemonSet","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","component":"azure-ip-masq-agent","kubernetes.io/cluster-service":"true","tier":"node"},"name":"azure-ip-masq-agent","namespace":"kube-system"},"spec":{"minReadySeconds":60,"selector":{"matchLabels":{"k8s-app":"azure-ip-masq-agent","tier":"node"}},"template":{"metadata":{"labels":{"k8s-app":"azure-ip-masq-agent","tier":"node"}},"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"labelSelector":null,"matchExpressions":[{"key":"kubernetes.azure.com/cluster","operator":"Exists"},{"key":"type","operator":"NotIn","values":["virtual-kubelet"]},{"key":"kubernetes.io/os","operator":"In","values":["linux"]}]}]}}},"containers":[{"args":["--v=2","--resync-interval=60"],"image":"mcr.microsoft.com/aks/ip-masq-agent-v2:v0.1.3","imagePullPolicy":"IfNotPresent","name":"azure-ip-masq-agent","resources":{"limits":{"cpu":"500m","memory":"250Mi"},"requests":{"cpu":"100m","memory":"50Mi"}},"securityContext":{"privileged":true},"volumeMounts":[{"mountPath":"/etc/config","name":"azure-ip-masq-agent-config-volume"},{"mountPath":"/run/xtables.lock","name":"iptableslock"}]}],"hostNetwork":true,"priorityClassName":"system-node-critical","tolerations":[{"key":"CriticalAddonsOnly","operator":"Exists"},{"effect":"NoExecute","operator":"Exists"},{"effect":"NoSchedule","operator":"Exists"}],"volumes":[{"name":"azure-ip-masq-agent-config-volume","projected":{"sources":[{"configMap":{"items":[{"key":"ip-masq-agent","mode":444,"path":"ip-masq-agent"}],"name":"azure-ip-masq-agent-config","optional":true}},{"configMap":{"items":[{"key":"ip-masq-agent-reconciled","mode":444,"path":"ip-masq-agent-reconciled"}],"name":"azure-ip-masq-agent-config-reconciled","optional":true}}]}},{"hostPath":{"path":"/run/xtables.lock","type":"FileOrCreate"},"name":"iptableslock"}]}},"updateStrategy":{"rollingUpdate":{"maxUnavailable":"25%"},"type":"RollingUpdate"}}}
  creationTimestamp: "2022-07-01T18:15:41Z"
  generation: 1
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    component: azure-ip-masq-agent
    kubernetes.io/cluster-service: "true"
    tier: node
  name: azure-ip-masq-agent
  namespace: kube-system
  resourceVersion: "1629"
  uid: 9da51cae-0400-40f7-aa18-e5724d5e8c56
spec:
  minReadySeconds: 60
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: azure-ip-masq-agent
      tier: node
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: azure-ip-masq-agent
        tier: node
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.azure.com/cluster
                operator: Exists
              - key: type
                operator: NotIn
                values:
                - virtual-kubelet
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      containers:
      - args:
        - --v=2
        - --resync-interval=60
        image: mcr.microsoft.com/aks/ip-masq-agent-v2:v0.1.3
        imagePullPolicy: IfNotPresent
        name: azure-ip-masq-agent
        resources:
          limits:
            cpu: 500m
            memory: 250Mi
          requests:
            cpu: 100m
            memory: 50Mi
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/config
          name: azure-ip-masq-agent-config-volume
        - mountPath: /run/xtables.lock
          name: iptableslock
      dnsPolicy: ClusterFirst
      hostNetwork: true
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
      volumes:
      - name: azure-ip-masq-agent-config-volume
        projected:
          defaultMode: 420
          sources:
          - configMap:
              items:
              - key: ip-masq-agent
                mode: 444
                path: ip-masq-agent
              name: azure-ip-masq-agent-config
              optional: true
          - configMap:
              items:
              - key: ip-masq-agent-reconciled
                mode: 444
                path: ip-masq-agent-reconciled
              name: azure-ip-masq-agent-config-reconciled
              optional: true
      - hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
        name: iptableslock
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 25%
    type: RollingUpdate
status:
  currentNumberScheduled: 3
  desiredNumberScheduled: 3
  numberAvailable: 3
  numberMisscheduled: 0
  numberReady: 3
  observedGeneration: 1
  updatedNumberScheduled: 3
