apiVersion: v1
kind: Pod
metadata:
  annotations:
    cluster-autoscaler.kubernetes.io/daemonset-pod: "true"
  creationTimestamp: "2022-07-01T18:16:25Z"
  generateName: cloud-node-manager-
  labels:
    controller-revision-hash: 79b7d44f67
    k8s-app: cloud-node-manager
    pod-template-generation: "1"
  name: cloud-node-manager-p9wpx
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: cloud-node-manager
    uid: 08fa0a44-ef4a-4074-82af-cb60e18f31db
  resourceVersion: "927"
  uid: 56b8ceae-67df-43a6-bc58-42db41f58d52
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - aks-agentpool-11515983-vmss000001
  containers:
  - command:
    - cloud-node-manager
    - --node-name=$(NODE_NAME)
    - --wait-routes
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: KUBERNETES_PORT_443_TCP_ADDR
      value: acldys-7ea05377.hcp.westeurope.azmk8s.io
    - name: KUBERNETES_PORT
      value: tcp://acldys-7ea05377.hcp.westeurope.azmk8s.io:443
    - name: KUBERNETES_PORT_443_TCP
      value: tcp://acldys-7ea05377.hcp.westeurope.azmk8s.io:443
    - name: KUBERNETES_SERVICE_HOST
      value: acldys-7ea05377.hcp.westeurope.azmk8s.io
    image: mcr.microsoft.com/oss/kubernetes/azure-cloud-node-manager:v1.1.14
    imagePullPolicy: IfNotPresent
    name: cloud-node-manager
    resources:
      limits:
        cpu: "2"
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 50Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-d9r76
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  nodeName: aks-agentpool-11515983-vmss000001
  preemptionPolicy: PreemptLowerPriority
  priority: 2000001000
  priorityClassName: system-node-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: cloud-node-manager
  serviceAccountName: cloud-node-manager
  terminationGracePeriodSeconds: 30
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoExecute
    operator: Exists
  - effect: NoSchedule
    operator: Exists
  volumes:
  - name: kube-api-access-d9r76
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-07-01T18:16:25Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-07-01T18:16:29Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-07-01T18:16:29Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-07-01T18:16:25Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://aa4e83fcb2f5ce0f81d4be83c6321306ff0a34872bfe898cf74e371bceca3a7f
    image: mcr.microsoft.com/oss/kubernetes/azure-cloud-node-manager:v1.1.14
    imageID: sha256:bd8a007d37e2609d61e496c1ef865246e771157511d0733af1348cab841b59a8
    lastState: {}
    name: cloud-node-manager
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-07-01T18:16:28Z"
  hostIP: 10.224.0.5
  phase: Running
  podIP: 10.224.0.5
  podIPs:
  - ip: 10.224.0.5
  qosClass: Burstable
  startTime: "2022-07-01T18:16:25Z"
