apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","kubernetes.io/bootstrapping":"rbac-defaults"},"name":"csi-azurefile-node-sa","namespace":"kube-system"}}
  creationTimestamp: "2022-07-01T18:15:42Z"
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/bootstrapping: rbac-defaults
  name: csi-azurefile-node-sa
  namespace: kube-system
  resourceVersion: "516"
  uid: b6ee22e7-66a1-4844-9f6c-c8d25a2ca31c
secrets:
- name: csi-azurefile-node-sa-token-w7lns
