apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2022-07-01T18:15:24Z"
  name: daemon-set-controller
  namespace: kube-system
  resourceVersion: "223"
  uid: e4bdb02a-381d-4a18-a41c-a1d405211ddb
secrets:
- name: daemon-set-controller-token-cq8bq
