apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2022-07-01T18:15:24Z"
  name: endpointslicemirroring-controller
  namespace: kube-system
  resourceVersion: "231"
  uid: b0545427-c3cf-44f8-bcad-303fde32d05c
secrets:
- name: endpointslicemirroring-controller-token-jqhc8
