apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2022-07-01T18:15:26Z"
  name: generic-garbage-collector
  namespace: kube-system
  resourceVersion: "300"
  uid: ad354bd8-a3ec-4de0-8d5e-7db09d9e09b6
secrets:
- name: generic-garbage-collector-token-p4qsp
