apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","kubernetes.io/cluster-service":"true"},"name":"metrics-server","namespace":"kube-system"}}
  creationTimestamp: "2022-07-01T18:15:42Z"
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/cluster-service: "true"
  name: metrics-server
  namespace: kube-system
  resourceVersion: "558"
  uid: c49a10fd-28fd-4caa-8d26-061ef18de898
secrets:
- name: metrics-server-token-kmxnp
