apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-07-01T18:15:20Z"
  labels:
    component: apiserver
    provider: kubernetes
  name: kubernetes
  namespace: default
  resourceVersion: "205"
  uid: 89797fe4-fe2b-4316-aa8b-2c015f6479b7
spec:
  clusterIP: 10.0.0.1
  clusterIPs:
  - 10.0.0.1
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
