apiVersion: v1
kind: Pod
metadata:
  labels:
    run: shell
  name: shell
spec:
  containers:
  - image: ivonet/ubuntu-dev
    command: ["/bin/sh", "-c", "while true; do echo 'Hello, world!'; sleep 5; done"]
    name: shell
    volumeMounts:
      - mountPath: /hostRoot
        name: root-hvm
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
    - name: root-hvm
      hostPath:
        path: /
